# Generated by Django 3.2.25 on 2024-11-27 07:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('fio', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('description', models.TextField(max_length=254, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='План помещения')),
                ('status', models.CharField(choices=[('Н', 'Новая'), ('П', 'Принято в работу'), ('В', 'Выполнено')], default='Н', max_length=100, verbose_name='Статус')),
                ('image_done', models.ImageField(blank=True, upload_to='image_done/', verbose_name='Готовое изображение')),
                ('comment', models.TextField(blank=True, max_length=254, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
